name: "Releases"
on:
  push:
    tags:
      - "*"
jobs:
  build-android:
    name: "Release apk"
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi --target-platform android-arm64
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/**/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
  build-ios:
    name: "Release iOS"
    runs-on: macos-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: env
      - run: pwd
      - run: ls -l build/ios/iphoneos/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "/Users/runner/runners/2.158.0/work/longnote/longnote/build/ios/iphoneos/Runner.ap*"
          token: ${{ secrets.GITHUB_TOKEN }}
