name: "Releases"
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: "Build & Release"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - run: flutter build ios --release --no-codesign
      - run: pwd
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "**/release/*.apk,/Users/runner/runners/2.158.0/work/longnote/longnote/build/ios/iphoneos/Runner.app."
          token: ${{ secrets.GITHUB_TOKEN }}
